export const FILTER_SEARCH = 'FILTER_SEARCH'
export const FILTER_LOCATION = 'FILTER_LOCATION'
export const FULLTIME_CHECK = 'FULLTIME_CHECK'
export const TOGGLE_SHOW_MOBILE = 'TOGGLE_SHOW_MOBILE'
export const CHECK_ACTIVE = 'CHECK_ACTIVE'

